// Generated by 'unplugin-auto-import'
export {}
declare global {
  const MyIconsChallenge: typeof import('~icons/my-icons/challenge.jsx')['default']
  const MyIconsCup: typeof import('~icons/my-icons/cup.jsx')['default']
  const MyIconsInfo: typeof import('~icons/my-icons/info.jsx')['default']
  const MyIconsKnife: typeof import('~icons/my-icons/knife.jsx')['default']
  const MyIconsMemo: typeof import('~icons/my-icons/memo.jsx')['default']
  const MyIconsMenu: typeof import('~icons/my-icons/menu.jsx')['default']
}
