// Generated by 'unplugin-auto-import'
export {}
declare global {
  const MyIconsCup: typeof import('~icons/my-icons/cup.jsx')['default']
  const MyIconsKnife: typeof import('~icons/my-icons/knife.jsx')['default']
}
